import {createRequire} from 'node:module';
import assert from 'node:assert/strict';
const require=createRequire(import.meta.resolve('wrangler/package.json'));
await require('esbuild').build({stdin:{contents:"export {POST} from './app/api/auth/[action]/route';export {getClientUser} from './lib/client-auth'",resolveDir:process.cwd()},bundle:true,format:'esm',platform:'node',outfile:'.sites-runtime/tests/auth.mjs',plugins:[{name:'test-only-context',setup(b){b.onResolve({filter:/^(cloudflare:workers|next\/headers)$/},a=>({path:a.path,namespace:'test'}));b.onLoad({filter:/.*/,namespace:'test'},a=>({contents:a.path==='cloudflare:workers'?'export const env=globalThis.testEnv;':'export async function cookies(){return {get:()=>globalThis.testCookie?{value:globalThis.testCookie}:undefined}}'}));}}]});
globalThis.testEnv={SUPABASE_URL:'https://auth.example.test',SUPABASE_PUBLISHABLE_KEY:'test',AUTH_EMAIL_READY:'true'};
globalThis.testCookie='';
const {POST,getClientUser}=await import('../.sites-runtime/tests/auth.mjs');
let calls=[];globalThis.fetch=async(url,init)=>{calls.push({url,init});if(url.endsWith('/user'))return Response.json({id:'client-1',email:'client@example.test',email_confirmed_at:'2026-09-11',is_anonymous:false});if(url.endsWith('/verify'))return Response.json({access_token:'synthetic-token',expires_in:3600});return Response.json({});};
const request=(action,body={},origin='https://jss.example.test')=>new Request(`https://jss.example.test/api/auth/${action}`,{method:'POST',headers:{origin,'Content-Type':'application/json'},body:JSON.stringify(body)});
assert.equal((await POST(request('send',{email:'client@example.test'},'https://evil.example'))).status,403);
assert.equal(calls.length,0);
testEnv.AUTH_EMAIL_READY='false';assert.equal((await POST(request('send'))).status,503);testEnv.AUTH_EMAIL_READY='true';
assert.equal((await POST(request('send',{email:'invalid'}))).status,400);
assert.equal((await POST(request('verify',{email:'client@example.test',code:'abc'}))).status,400);
await POST(request('send',{email:'client@example.test',register:false}));assert.equal(JSON.parse(calls.at(-1).init.body).create_user,false);
await POST(request('send',{email:'client@example.test',register:true}));assert.equal(JSON.parse(calls.at(-1).init.body).create_user,true);
const result=await POST(request('verify',{email:'client@example.test',code:'123456'}));assert.equal(result.status,200);const cookie=result.headers.get('set-cookie');for(const s of ['__Host-jss_session=','HttpOnly','Secure','SameSite=Lax','Max-Age=3600'])assert.ok(cookie.includes(s));assert.deepEqual(await result.json(),{ok:true});
assert.equal(await getClientUser(),null);testCookie='synthetic-token';assert.equal((await getClientUser()).userId,'supabase:client-1');
const normalFetch=globalThis.fetch;globalThis.fetch=async()=>Response.json({error:'invalid'},{status:401});assert.equal(await getClientUser(),null);assert.equal((await POST(request('verify',{email:'client@example.test',code:'123456'}))).status,400);
globalThis.fetch=async()=>Response.json({id:'client-1',email:'client@example.test'});assert.equal(await getClientUser(),null);
globalThis.fetch=normalFetch;assert.ok((await POST(request('logout'))).headers.get('set-cookie').includes('Max-Age=0'));
console.log('PASS 12 auth scenarios: origin, disabled, invalid input/code, sign-in/registration distinction, verified cookie, anonymous/invalid/unconfirmed rejection, identity namespace, logout. Provider mocked; no emails sent.');
