import {createRequire} from 'node:module';
import {readFile,mkdir} from 'node:fs/promises';
import assert from 'node:assert/strict';
const require=createRequire(import.meta.resolve('wrangler/package.json'));
const {build}=require('esbuild');const {Miniflare}=require('miniflare');
await mkdir('.sites-runtime/tests',{recursive:true});
// Auth shim is confined to this test bundle; production uses dispatch-owned SIWC.
await build({stdin:{contents:"import {GET,POST} from './app/api/ros/[...path]/route'; import {applyPayment} from './lib/payments'; export default {async fetch(r){if(new URL(r.url).pathname==='/__test_payment'){try{const v=await r.json();return Response.json(await applyPayment(v.session,v.event))}catch(e){return Response.json({error:e.message},{status:e.status||500})}}globalThis.__testHeaders=r.headers;return r.method==='GET'?GET(r):POST(r)}}",resolveDir:process.cwd()},bundle:true,format:'esm',platform:'neutral',conditions:['workerd','worker'],outfile:'.sites-runtime/tests/worker.mjs',external:['cloudflare:workers'],plugins:[{name:'test-auth-only',setup(b){b.onLoad({filter:/route\.ts$/},async(args)=>({contents:(await readFile(args.path,'utf8')).replace("e instanceof Error?e.name:'Error'","e instanceof Error?e.stack:'Error'"),loader:'ts'}));b.onResolve({filter:/^@\/app\/chatgpt-auth$/},()=>({path:'test-auth',namespace:'test'}));b.onLoad({filter:/.*/,namespace:'test'},()=>({contents:"export async function getChatGPTUser(){const h=globalThis.__testHeaders;const userId=h.get('x-test-user'),email=h.get('x-test-email');return userId&&email?{userId,email,displayName:email,fullName:null}:null}"}));}}]});
const mf=new Miniflare({modules:true,scriptPath:'.sites-runtime/tests/worker.mjs',compatibilityDate:'2026-05-15',d1Databases:['DB'],r2Buckets:['BUCKET'],bindings:{OWNER_EMAILS:'operator@example.test',PAYMENTS_ENABLED:'false',EMAIL_ENABLED:'false',STRIPE_WEBHOOK_SECRET:'whsec_synthetic_only',STRIPE_SECRET_KEY:'rk_test_synthetic_only'},cf:false});
let passed=0;const test=async(name,fn)=>{await fn();passed++;console.log('PASS '+name)};
try{const db=await mf.getD1Database('DB');const sql=await readFile('drizzle/0000_steady_nico_minoru.sql','utf8');for(const stmt of sql.split('--> statement-breakpoint').map(x=>x.trim()).filter(Boolean))await db.prepare(stmt).run();
const identity={alice:['client-a','alice@example.test'],bob:['client-b','bob@example.test'],operator:['operator','operator@example.test']};
async function req(path,{who='alice',body,method=body?'POST':'GET',headers={}}={}){const [uid,email]=identity[who]||[];const h={...(uid?{'x-test-user':uid,'x-test-email':email}:{}),...(body?{'Content-Type':'application/json'}:{}),...headers};return mf.dispatchFetch('https://unit.test/api/ros/'+path,{method,headers:h,body:body?JSON.stringify(body):undefined})}
const intake={fullName:'Alice Test',serviceNeeded:'Business Funding',state:'GA',mainGoal:'Build a documented funding readiness plan',businessName:'Test Example LLC',entity:'LLC',businessMonths:12,monthlyRevenue:5000,fundingAmount:25000,ein:true,bank:false,bookkeeping:false,consent:true,reminders:true,requestKey:crypto.randomUUID()};let caseId,docId;
await test('anonymous access rejected',async()=>assert.equal((await req('cases',{who:'anonymous'})).status,401));
await test('invalid intake creates no record',async()=>{assert.equal((await req('cases',{body:{...intake,consent:false}})).status,400);assert.equal((await db.prepare('SELECT count(*) n FROM cases').first()).n,0)});
await test('intake atomically creates case and released free brief',async()=>{const r=await req('cases',{body:intake});assert.equal(r.status,201);caseId=(await r.json()).id;const c=await(await req('cases/'+caseId)).json();assert.equal(c.deliverables.length,1);assert.equal(c.deliverables[0].status,'released');assert.match(c.deliverables[0].body,/Separate business banking/)});
await test('replayed intake is idempotent',async()=>{const d=await(await req('cases',{body:intake})).json();assert.equal(d.id,caseId);assert.equal((await db.prepare('SELECT count(*) n FROM cases').first()).n,1)});
await test('other client cannot read case',async()=>assert.equal((await req('cases/'+caseId,{who:'bob'})).status,404));
await test('client cannot enumerate operator records',async()=>assert.equal((await req('cases?all=1')).status,403));
await test('cross-origin mutations rejected',async()=>assert.equal((await req('cases',{body:intake,headers:{Origin:'https://evil.test'}})).status,403));
await test('client cannot assign workflow stage',async()=>assert.equal((await req('cases/'+caseId+'/status',{body:{status:'scope_approved'}})).status,403));
await test('scope approval requires written terms',async()=>assert.equal((await req('cases/'+caseId+'/status',{who:'operator',body:{status:'scope_approved'}})).status,400));
await test('operator approves written scope and client accepts exact version',async()=>{const r=await req('cases/'+caseId+'/status',{who:'operator',body:{status:'scope_approved',scope:'SYNTHETIC TEST SCOPE: a funding readiness report after document review. Delivery in ten business days after all records are provided. Cancellation before work begins permits a full refund; third-party costs are excluded.'}});assert.equal(r.status,200);const d=await(await req('cases/'+caseId)).json();assert.equal((await req('cases/'+caseId+'/accept-scope',{body:{version:'stale',accepted:true}})).status,409);assert.equal((await req('cases/'+caseId+'/accept-scope',{body:{version:d.scope.version,accepted:true}})).status,200)});
await test('unconfigured payments fail closed',async()=>assert.equal((await req('cases/'+caseId+'/checkout',{body:{}})).status,503));
await test('unsigned payment webhook rejected',async()=>assert.equal((await req('webhook',{who:'anonymous',body:{type:'checkout.session.completed'}})).status,400));
await test('PDF upload persists bytes and metadata',async()=>{const f=new FormData();f.set('file',new File(['%PDF-1.7\nsynthetic fixture'],'record.pdf',{type:'application/pdf'}));const upload=new Request('https://unit.test/api/ros/cases/'+caseId+'/documents',{method:'POST',headers:{'x-test-user':'client-a','x-test-email':'alice@example.test'},body:f});const r=await mf.dispatchFetch(upload.url,{method:'POST',headers:Object.fromEntries(upload.headers),body:new Uint8Array(await upload.arrayBuffer())});assert.equal(r.status,201);docId=(await r.json()).id;const out=await req('documents/'+docId);assert.equal(out.status,200);assert.match(out.headers.get('content-disposition'),/^attachment/);assert.match(await out.text(),/%PDF-1.7/)});
await test('other client cannot download private document',async()=>assert.equal((await req('documents/'+docId,{who:'bob'})).status,404));
await test('disguised upload rejected',async()=>{const f=new FormData();f.set('file',new File(['<script>bad</script>'],'fake.pdf',{type:'application/pdf'}));const upload=new Request('https://unit.test/api/ros/cases/'+caseId+'/documents',{method:'POST',headers:{'x-test-user':'client-a','x-test-email':'alice@example.test'},body:f});const r=await mf.dispatchFetch(upload.url,{method:'POST',headers:Object.fromEntries(upload.headers),body:new Uint8Array(await upload.arrayBuffer())});assert.equal(r.status,400)});
await test('repeated reminder checks create no duplicate messages',async()=>{await db.prepare('UPDATE cases SET created_at=? WHERE id=?').bind(new Date(Date.now()-8*86400000).toISOString(),caseId).run();await req('admin/queue',{who:'operator',body:{}});await req('admin/queue',{who:'operator',body:{}});assert.equal((await db.prepare('SELECT count(*) n FROM outbox').first()).n,3);assert.equal((await db.prepare("SELECT count(*) n FROM outbox WHERE status='sent'").first()).n,0)});
await test('consent withdrawal cancels queued reminders',async()=>{assert.equal((await req('cases/'+caseId+'/reminders',{body:{enabled:false}})).status,200);assert.equal((await db.prepare("SELECT count(*) n FROM outbox WHERE status='pending'").first()).n,0)});
await test('client cannot release deliverables',async()=>{const d=await db.prepare('SELECT id FROM deliverables WHERE case_id=?').bind(caseId).first();assert.equal((await req('deliverables/'+d.id,{body:{action:'release',reviewed:true}})).status,403)});
await test('released deliverable is immutable',async()=>{const d=await db.prepare('SELECT id FROM deliverables WHERE case_id=?').bind(caseId).first();assert.equal((await req('deliverables/'+d.id,{who:'operator',body:{action:'save',body:'overwrite'}})).status,409)});
await test('credit lane cannot enter generic payment scope',async()=>{const res=await(await req('cases',{body:{...intake,serviceNeeded:'Credit Review',requestKey:crypto.randomUUID()}})).json();assert.equal((await req('cases/'+res.id+'/status',{who:'operator',body:{status:'scope_approved',scope:'x'.repeat(150)}})).status,409)});
await test('unauthorized scheduler rejected',async()=>assert.equal((await req('tick',{who:'anonymous',body:{}})).status,401));

let paymentSession={id:'cs_test_synthetic_session',status:'complete',payment_status:'paid',mode:'payment',amount_total:30000,currency:'usd',livemode:false,metadata:{case_id:caseId,offer:'funding_blueprint'}};
async function pay(session,event){return mf.dispatchFetch('https://unit.test/__test_payment',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({session,event})})}
await test('mismatched payment amount is rejected',async()=>assert.equal((await pay({...paymentSession,amount_total:1},'evt_wrong')).status,400));
await test('mismatched payment currency is rejected',async()=>assert.equal((await pay({...paymentSession,currency:'eur'},'evt_wrong_currency')).status,400));
await test('mismatched payment mode is rejected',async()=>assert.equal((await pay({...paymentSession,livemode:true},'evt_wrong_mode')).status,400));
await test('payment replay creates one receipt and one draft',async()=>{assert.equal((await pay(paymentSession,'evt_synthetic_1')).status,200);assert.equal((await pay(paymentSession,'evt_synthetic_2')).status,200);assert.equal((await db.prepare('SELECT count(*) n FROM payments').first()).n,1);assert.equal((await db.prepare("SELECT count(*) n FROM deliverables WHERE kind='funding_blueprint'").first()).n,1);const d=await(await req('cases/'+caseId)).json();assert.equal(d.case.payment_status,'test_paid');assert.equal(d.deliverables.length,1)});
await test('draft cannot release without reviewer attestation',async()=>{const d=await db.prepare("SELECT id FROM deliverables WHERE kind='funding_blueprint'").first();assert.equal((await req('deliverables/'+d.id,{who:'operator',body:{action:'release',reviewed:false}})).status,400)});
await test('reviewed paid draft appears in client portal on release',async()=>{const d=await db.prepare("SELECT id FROM deliverables WHERE kind='funding_blueprint'").first();assert.equal((await req('deliverables/'+d.id,{who:'operator',body:{action:'release',reviewed:true}})).status,200);const out=await(await req('cases/'+caseId)).json();assert.equal(out.case.status,'delivered');assert.equal(out.deliverables.length,2)});
await test('admin revenue excludes unpaid and test records',async()=>{const d=await(await req('admin/overview',{who:'operator'})).json();assert.equal(d.payment.amount,0);assert.equal(d.readiness.payments,false)});
console.log(`RESULT ${passed} integration checks passed. No external messages or charges.`);
}finally{await mf.dispose()}
