import {z} from 'zod';
export const lanes=['Business Funding','Business Setup','Credit Review','Automation / AI Systems','Platform Setup','Consultation'] as const;
export const intakeSchema=z.object({fullName:z.string().trim().min(2).max(100),serviceNeeded:z.enum(lanes),state:z.string().trim().min(2).max(50),mainGoal:z.string().trim().min(15).max(2000),businessName:z.string().trim().max(150).default(''),entity:z.enum(['Not formed','LLC','Corporation','Sole proprietor','Other']).default('Not formed'),businessMonths:z.coerce.number().int().min(0).max(1200),monthlyRevenue:z.coerce.number().min(0).max(1e9),fundingAmount:z.coerce.number().min(0).max(1e9),ein:z.boolean(),bank:z.boolean(),bookkeeping:z.boolean(),consent:z.literal(true),reminders:z.boolean().default(false),requestKey:z.string().uuid()}).strict();
export type Intake=z.infer<typeof intakeSchema>;
export const PRICE=30000;
export const TERMS_VERSION='2026-09-11-v1';
export function classify(i:Intake){return {lane:i.serviceNeeded,tier:i.serviceNeeded==='Business Funding'?'T2 Strategy Build':i.serviceNeeded==='Automation / AI Systems'||i.serviceNeeded==='Platform Setup'?'T4 System Build':'T1 Diagnosis',status:i.serviceNeeded==='Credit Review'?'compliance_review':'review_pending'};}
export function makeBrief(i:Intake){const missing=[];if(i.entity==='Not formed')missing.push('Confirm the appropriate business structure and formation status.');if(!i.ein)missing.push('Gather EIN confirmation and verify that the business name matches your records.');if(!i.bank)missing.push('Separate business banking from personal transactions.');if(!i.bookkeeping)missing.push('Prepare current bookkeeping, an income statement, and a balance sheet.');if(i.monthlyRevenue===0)missing.push('Document startup resources and a realistic operating budget. Reported revenue is currently zero.');
const focus=i.serviceNeeded==='Credit Review'?['Obtain current reports from each relevant bureau.','Identify each disputed field and supporting evidence; do not dispute information merely because it is negative.','Wait for jurisdiction and service-agreement review before paid credit services or dispute dispatch.']:i.serviceNeeded.includes('Automation')||i.serviceNeeded==='Platform Setup'?['Document the current intake-to-delivery process and the systems already used.','Define the first workflow, required access, success criteria, and exception owner.','Test with synthetic records before activating client communications.']:missing.length?missing:['Reconcile the business information across formation, EIN, banking, and bookkeeping records.','Collect current financial documents for a verified review.'];
return `INITIAL READINESS BRIEF\n${i.fullName} • ${i.serviceNeeded}\n\nYOUR OBJECTIVE\n${i.mainGoal}\n\nINFORMATION YOU PROVIDED\nBusiness: ${i.businessName||'Not provided'}\nState: ${i.state}\nStructure: ${i.entity}\nOperating history: ${i.businessMonths} months\nMonthly revenue: $${i.monthlyRevenue.toLocaleString('en-US')} (self-reported)\nFunding goal: $${i.fundingAmount.toLocaleString('en-US')}\n\nPRIORITY ACTIONS\n${focus.map((v,n)=>`${n+1}. ${v}`).join('\n')}\n\nNEXT STEP\nUpload relevant business records in your portal. An operator will review evidence and confirm any paid scope before execution.\n\nBASIS AND LIMITS\nThis free, rules-based planning brief uses only your intake answers. No credit file, bank statement, lender criteria, or legal eligibility has been independently verified. It is not an approval, credit score prediction, legal opinion, or promise of financing.`;}
export function makeBlueprint(i:Intake){return `${makeBrief(i)}\n\nSTRATEGY WORKING DRAFT — OPERATOR REVIEW REQUIRED\n\nWEEK 1 · DOCUMENT THE BASELINE\nCreate one consistent business profile. Gather formation records, EIN notice, ownership information, business bank statements, current financial statements, and tax returns where available. Mark unavailable documents explicitly.\n\nWEEK 2 · RESOLVE FOUNDATION GAPS\n${!i.bank?'Establish a dedicated business account.':'Reconcile the existing business account.'} ${!i.bookkeeping?'Set up monthly bookkeeping and a cash-flow view.':'Update bookkeeping through the last closed month.'} Build a use-of-funds schedule for the stated $${i.fundingAmount.toLocaleString('en-US')} goal; separate one-time expenses from recurring costs.\n\nWEEK 3 · VALIDATE OPTIONS\n${i.businessMonths<24?'Limited operating history: investigate startup eligibility directly with candidate providers; do not assume conventional loan qualification.':'Operating history is self-reported: compare documented history against current provider criteria.'} Compare repayment frequency, total borrowing cost, collateral, guarantees, fees, and cash-flow impact using written terms. No specific lender is recommended until current criteria and the submitted evidence are reviewed.\n\nWEEK 4 · CONTROL EXECUTION\nComplete a readiness review before any application. Verify consent for credit inquiries and submit only approved applications. Record decisions, missing information, and follow-up dates in the case file. Do not inflate revenue, alter documents, or reuse stale financial figures.\n\nOPERATOR COMPLETION REQUIRED\nConfirm evidence, service scope, suitable provider options, affordability assumptions, and relevant state requirements. Replace or supplement this working draft with the reviewed client-specific strategy before release.`;}
export function canRead(user:string,owner:string,isAdmin:boolean){return isAdmin||user===owner;}
export function paymentValid(s:any,c:any,live:boolean){return s.status==='complete'&&s.payment_status==='paid'&&s.mode==='payment'&&s.amount_total===PRICE&&s.currency==='usd'&&s.livemode===live&&s.metadata?.case_id===c.id&&s.metadata?.offer==='funding_blueprint'&&c.lane==='Business Funding';}
export async function verifyStripe(raw:string,header:string,secret:string,now=Date.now()){const pairs=header.split(',').map(x=>x.split('='));const t=pairs.find(x=>x[0]==='t')?.[1];const signatures=pairs.filter(x=>x[0]==='v1').map(x=>x[1]);if(!t||!/^\d+$/.test(t)||Math.abs(now/1000-Number(t))>300)return false;const key=await crypto.subtle.importKey('raw',new TextEncoder().encode(secret),{name:'HMAC',hash:'SHA-256'},false,['sign']);const signed=await crypto.subtle.sign('HMAC',key,new TextEncoder().encode(`${t}.${raw}`));const hex=Array.from(new Uint8Array(signed),b=>b.toString(16).padStart(2,'0')).join('');return signatures.some(v=>{if(v.length!==hex.length)return false;let diff=0;for(let n=0;n<v.length;n++)diff|=v.charCodeAt(n)^hex.charCodeAt(n);return diff===0;});}
